// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/8/2025, 8:45:29 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/miguelfondeur/Desktop/project 3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miguelfondeur/Desktop/project 3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miguelfondeur/Desktop/project 3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miguelfondeur/Desktop/project 3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miguelfondeur/Desktop/project 3/plugins/**/*.{js,ts,mjs}","/Users/miguelfondeur/Desktop/project 3/composables/**/*.{js,ts,mjs}","/Users/miguelfondeur/Desktop/project 3/utils/**/*.{js,ts,mjs}","/Users/miguelfondeur/Desktop/project 3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miguelfondeur/Desktop/project 3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/miguelfondeur/Desktop/project 3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/miguelfondeur/Desktop/project 3/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;